version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  web:
    build: .
    container_name: web
    ports:
      - 80:80
    environment:
      DB_HOST: db
      DB_NAME: admin
      DB_USER: admin
      DB_PASS: admin
      DB_PORT: 5432
      WWWROOT: http://localhost
      